-- ============================================================================
-- TEMPLATE: Blogging & Hosting cluster — manual article inserts
-- ============================================================================
-- Purpose:
--   This file is a TEMPLATE for inserting your hand-written markdown articles
--   into Supabase `public.articles`. You write in
--   `content/drafts/<category>/<slug>.md` (source of truth), then run
--   `npm run article:publish <slug>` to upsert that file into Supabase with
--   `status='draft'`. This SQL file shows the equivalent manual SQL you could
--   run in Supabase SQL Editor if you prefer.
--
--   All INSERTs below are COMMENTED OUT intentionally — uncomment and edit
--   only when you are ready to insert a real, human-written article.
--   No AI-generated drafts are included; content/drafts/blogging-hosting/*.md
--   were removed per Phase 4 (you write one article at a time).
--
-- Usage:
--   1. Write: npm run article:new my-slug -- --category="Blogging & Hosting"
--      → creates content/drafts/blogging-hosting/my-slug.md
--   2. Publish (draft): npm run article:publish my-slug
--      → parses frontmatter, upserts to Supabase with status='draft'
--   3. Verify in Supabase:
--      SELECT slug, status, title FROM articles WHERE slug='my-slug';
--      (draft is NOT visible on /blog/my-slug publicly; only via preview if you allow)
--   4. When ready to go live (after you verified NPR pricing/screenshots):
--      UPDATE articles SET status='published', published_at=CURRENT_DATE
--      WHERE slug='my-slug';
--   5. Revert to draft if needed:
--      UPDATE articles SET status='draft' WHERE slug='my-slug';
--
-- Affiliate links: Use placeholders via env vars only
--   (e.g., NEXT_PUBLIC_AFFILIATE_HOSTINGER_URL). Never hardcode IDs.
--   See lib/affiliates.js for the map.
-- ============================================================================

-- Example (COMMENTED OUT — copy, uncomment, and replace with your real markdown):
-- ----------------------------------------------------------------------------
-- -- Pre-check: no slug collision
-- -- SELECT slug, status FROM articles WHERE slug IN ('my-slug');
--
-- INSERT INTO public.articles (
--   id, author_id, title, slug, category, target_keyword,
--   meta_description, image_url, content, seo_score, status, published_at
-- )
-- VALUES (
--   gen_random_uuid(),
--   '00000000-0000-0000-0000-000000000000'::uuid, -- replace with your profiles.id for real byline
--   'My Honest Title (2026) — Tested in Nepal',
--   'my-slug',
--   'Blogging & Hosting',
--   'my keyword',
--   'Meta description ~155 chars, honest, no fake claims.',
--   'https://images.unsplash.com/photo-...?auto=format&fit=crop&w=1200&q=80',
--   $md$--- paste full markdown body from content/drafts/blogging-hosting/my-slug.md here ---$md$,
--   85,
--   'draft',
--   CURRENT_DATE
-- )
-- ON CONFLICT (slug) DO NOTHING;
--
-- -- Verify:
-- -- SELECT slug, title, status, category, length(content) FROM articles WHERE slug='my-slug';
--
-- -- Publish (only after you verified real screenshots & NPR):
-- -- UPDATE articles SET status='published', published_at=CURRENT_DATE, updated_at=NOW() WHERE slug='my-slug';
--
-- -- Revert to draft:
-- -- UPDATE articles SET status='draft', updated_at=NOW() WHERE slug='my-slug';
-- ----------------------------------------------------------------------------

-- Previously auto-generated Hostinger drafts were removed.
-- If you need to re-insert a published test article, use article:publish or the template above.

-- End of template
