export const resourceCategories = [
	{
		id: "ai-tools",
		title: "AI Tools",
		emoji: "🤖",
		pillar: "/ai-tools",
		audience: "Students, freelancers, and creators who need affordable AI help that works on Nepali internet.",
		resources: [
			{ name: "ChatGPT", url: "https://chatgpt.com", badge: "🔶", status: "🛡️", why: "Best all-round free AI; works on NTC/Ncell data, no VPN." },
			{ name: "Gemini", url: "https://gemini.google.com", badge: "🔶", status: "✅", why: "One Google login; plugs into Gmail and Docs students already use." },
			{ name: "DeepSeek", url: "https://chat.deepseek.com", badge: "🆓", status: "✅", why: "Free and excellent at code/math; CS students' best free tutor." },
			{ name: "Meta AI", url: "https://www.meta.ai", badge: "🆓", status: "🛡️", why: "Inside WhatsApp, Instagram, and Facebook already; zero new signup for beginners." },
			{ name: "Google AI Studio", url: "https://aistudio.google.com", badge: "🔶", status: "✅", why: "Free API playground; freelancers can build client chatbot demos free." },
			{ name: "Bing Image Creator", url: "https://www.bing.com/images/create", badge: "🆓", status: "✅", why: "Near-unlimited free AI images for blogs, thumbnails, and mockups." },
			{ name: "Harper", url: "https://writewithharper.com", badge: "🆓", status: "✅", why: "Free, private grammar checker for Upwork proposals and CVs." },
			{ name: "QuillBot", url: "https://quillbot.com/grammar-check", badge: "🔶", status: "🛡️", why: "Paraphrase and grammar help; free tier is enough for many students." },
			{ name: "DeepL Translator", url: "https://www.deepl.com/translator", badge: "🔶", status: "✅", why: "Strong English-to-European-language quality for Upwork client communication." },
			{ name: "DeepL Write", url: "https://www.deepl.com/write", badge: "🔶", status: "✅", why: "AI rewrite and polish; pairs well with DeepL Translator." },
			{ name: "ElevenLabs", url: "https://elevenlabs.io", badge: "🔶", status: "✅", why: "Human-like voiceovers for faceless YouTube and client demos." },
			{ name: "TurboScribe", url: "https://turboscribe.ai", badge: "🔶", status: "🛡️", why: "Lecture and meeting transcription with free daily minutes." },
			{ name: "Whisper", url: "https://github.com/openai/whisper", badge: "🆓", status: "✅", why: "Free offline transcription for private client calls." },
			{ name: "NVIDIA NIM", url: "https://build.nvidia.com/models", badge: "🆓", status: "✅", why: "Try top AI models with no signup." },
			{ name: "Ecosia AI", url: "https://www.ecosia.org/ai-chat", badge: "🆓", status: "🛡️", why: "Unlimited chat, no account, plus an eco angle." },
			{ name: "Grammarly", url: null, affiliate: true, badge: "💳", why: "Premium polish for client work. Verify NPR pricing before publishing." },
			{ name: "Canva", url: null, affiliate: true, badge: "🔶", why: "Design posts and thumbnails; free tier plus Pro affiliate. Verify NPR." },
		],
	},
	{
		id: "freelancing",
		title: "Freelancing",
		emoji: "💼",
		pillar: "/freelancing-in-nepal",
		audience: "Profile, proposal, portfolio, and remote-work tools for Nepali freelancers.",
		resources: [
			{ name: "RX Resume", url: "https://rxresu.me", badge: "🆓", status: "✅", why: "Free, beautiful CV builder; export PDF for job mails." },
			{ name: "FlowCV", url: "https://flowcv.com", badge: "🔶", status: "✅", why: "Resume builder with templates; free tier works." },
			{ name: "RenderCV", url: "https://rendercv.com", badge: "🆓", status: "✅", why: "Markdown CVs developers love; clean PDFs." },
			{ name: "PeerList", url: "https://peerlist.io", badge: "🆓", status: "✅", why: "Portfolio network for developers/designers; alternative to a full website." },
			{ name: "Carrd", url: "https://carrd.co", badge: "🔶", status: "✅", why: "One-page freelancer site in an hour; free tier plus cheap Pro." },
			{ name: "Linkstack", url: "https://linkstack.org", badge: "🆓", status: "✅", why: "Free self-hosted link-in-bio; own your links." },
			{ name: "Real Work From Anywhere", url: "https://www.realworkfromanywhere.com", badge: "🆓", status: "✅", why: "Remote board with Asia-friendly roles." },
			{ name: "Remote in Tech index", url: "https://remoteintech.company", badge: "🆓", status: "✅", why: "See which companies hire remotely and build a target list." },
			{ name: "Nomad List", url: "https://nomads.com", badge: "🔶", status: "✅", why: "See remote pay and cost data; Kathmandu data point exists." },
			{ name: "WorldTimeBuddy", url: "https://www.worldtimebuddy.com", badge: "🆓", status: "✅", why: "Compare Nepal Time with client time zones so calls are never missed." },
			{ name: "SimpleLogin", url: "https://simplelogin.io", badge: "🔶", status: "✅", why: "Professional email aliases for client work; hide personal Gmail." },
			{ name: "RolePad", url: "https://rolepad.com", badge: "🆓", status: "✅", why: "Track job applications in one board." },
			{ name: "Notion", url: null, affiliate: true, badge: "🔶", why: "Proposals and client wikis. Verify NPR pricing." },
		],
	},
	{
		id: "hosting",
		title: "Blogging & Hosting",
		emoji: "🌐",
		pillar: "/blogging-hosting",
		audience: "Domains, hosting, static sites, and content tools for Nepali bloggers.",
		resources: [
			{ name: "Hostinger", env: "NEXT_PUBLIC_AFFILIATE_HOSTINGER_URL", affiliate: true, badge: "💳", why: "Primary pick; eSewa-linked cards work; LiteSpeed is fast on NTC. Verify intro and renewal NPR." },
			{ name: "Cloudflare", url: "https://www.cloudflare.com", affiliate: true, badge: "🆓", why: "Free CDN/DNS; reduces load time from Nepal and no card needed for free tier." },
			{ name: "Namecheap", url: null, affiliate: true, badge: "💳", why: "Domains only; keep domain separate from host. Verify NPR." },
			{ name: "WordPress.com", url: null, affiliate: true, badge: "🔶", why: "Zero-hassle publishing for non-technical beginners. Verify NPR." },
			{ name: "Cloudflare Pages", url: "https://www.cloudflare.com/products/pages", badge: "🆓", status: "✅", why: "Free unlimited-bandwidth static hosting; test before buying." },
			{ name: "GitHub Pages", url: "https://docs.github.com/en/pages", badge: "🆓", status: "✅", why: "Free portfolio/blog hosting for technical users." },
			{ name: "Vercel", url: "https://vercel.com", badge: "🔶", status: "✅", why: "Free hobby hosting for Next.js and static sites." },
			{ name: "Astro", url: "https://astro.build", badge: "🆓", status: "✅", why: "Blazing static sites; great blog framework." },
			{ name: "Hugo", url: "https://gohugo.io", badge: "🆓", status: "✅", why: "Single-binary static generator; low-end-laptop friendly." },
			{ name: "Bear Blog", url: "https://bearblog.dev", badge: "🔶", status: "🛡️", why: "Minimalist paid-simple blogging; distraction-free." },
			{ name: "LocalWP", url: "https://localwp.com", badge: "🆓", status: "✅", why: "Free local WordPress practice before paying for hosting." },
			{ name: "TinyURL", url: "https://tinyurl.com", badge: "🆓", status: "✅", why: "Short links for social promos." },
			{ name: "CoverView", url: "https://coverview.vercel.app", badge: "🆓", status: "✅", why: "Free blog banners and covers." },
		],
	},
	{
		id: "payments",
		title: "Digital Payments",
		emoji: "💳",
		pillar: "/digital-payments",
		audience: "Receive USD, compare fees, and keep local-wallet workflows clear.",
		resources: [
			{ name: "Payoneer", url: null, affiliate: true, badge: "🔶", why: "Receive USD and withdraw to a Nepali bank. Verify fees/limits for Sept 2026." },
			{ name: "Wise", url: null, affiliate: true, badge: "🔶", why: "Low-fee transfers; compare against Payoneer and verify NPR rails." },
			{ name: "eSewa / Khalti", url: null, badge: "ℹ️", why: "Local wallets for local client payments and linked-card hosting workflows. Verify current card-linking." },
			{ name: "Upwork direct to bank", url: null, badge: "ℹ️", why: "US clients to Upwork to Nepali bank pipeline; document fees before publishing." },
		],
	},
	{
		id: "business",
		title: "Small Business Tools",
		emoji: "🏪",
		pillar: "/small-business-tools",
		audience: "Free and low-cost tools for a Nepali pasal, local service, or Facebook shop.",
		resources: [
			{ name: "Photopea", url: "https://www.photopea.com", badge: "🆓", status: "✅", why: "Free Photoshop in a browser for menus, price lists, and social posts." },
			{ name: "LibreOffice", url: "https://www.libreoffice.org", badge: "🆓", status: "✅", why: "Free Office; bills, invoices, stock sheets, and Nepali text." },
			{ name: "OnlyOffice", url: "https://www.onlyoffice.com", badge: "🆓", status: "✅", why: "MS-compatible alternative if LibreOffice formatting breaks." },
			{ name: "Obsidian", url: "https://obsidian.md", badge: "🆓", status: "✅", why: "Notes and inventory ideas; works offline during power cuts." },
			{ name: "BentoPDF", url: "https://bentopdf.com", badge: "🆓", status: "✅", why: "Private client-side PDF tools for quotations and invoices." },
			{ name: "Unsplash", url: "https://unsplash.com", badge: "🆓", status: "✅", why: "Free product/lifestyle photos for social pages." },
			{ name: "Pixabay", url: "https://pixabay.com", badge: "🆓", status: "🛡️", why: "Second free stock source." },
			{ name: "Squoosh", url: "https://squoosh.app", badge: "🆓", status: "✅", why: "Shrink product photos so pages load on 4G." },
			{ name: "Pixelcut", url: "https://www.pixelcut.ai", badge: "🔶", status: "✅", why: "One-click product background remover for Daraz and Facebook shops." },
			{ name: "OCR.space", url: "https://ocr.space", badge: "🆓", status: "✅", why: "Scan paper bills to text free." },
			{ name: "MEGA", url: "https://mega.io", badge: "🔶", status: "✅", why: "20 GB free to back up shop records off the phone." },
			{ name: "Filen", url: "https://filen.io", badge: "🔶", status: "✅", why: "10 GB free encrypted backup." },
			{ name: "Bitwarden", url: "https://bitwarden.com", badge: "🆓", status: "✅", why: "Free password manager; stop reusing one password everywhere." },
			{ name: "Ente Auth", url: "https://ente.com/auth", badge: "🆓", status: "✅", why: "Free 2FA app for Gmail, eSewa, and bank logins." },
			{ name: "uBlock Origin", url: "https://github.com/gorhill/uBlock", badge: "🆓", status: "✅", why: "Block scam ads and malware on shop PCs." },
			{ name: "Super Productivity", url: "https://super-productivity.com", badge: "🆓", status: "✅", why: "Free time/task tracker for tiny teams." },
			{ name: "Ente QR / Mini QR", url: "https://qr.ente.com", secondaryUrl: "https://mini-qr-code-generator.vercel.app", badge: "🆓", status: "✅", why: "Free QR codes for menus, payments, and cards." },
			{ name: "Daraz", url: null, affiliate: true, badge: "🔶", why: "SMB selling channel. Verify affiliate program terms." },
		],
	},
	{
		id: "students",
		title: "Students & Learning",
		emoji: "🎓",
		pillar: "/resources#students",
		audience: "Free learning, coding, books, English, and exam prep resources.",
		resources: [
			{ name: "MIT OpenCourseWare", url: "https://ocw.mit.edu", badge: "🆓", status: "✅", why: "Real MIT courses free; CS and math gold." },
			{ name: "Khan Academy", url: "https://www.khanacademy.org", badge: "🆓", status: "✅", why: "+2 Science and test prep; low-data friendly." },
			{ name: "edX", url: "https://www.edx.org", badge: "🔶", status: "✅", why: "University courses; audit many courses free." },
			{ name: "The Odin Project", url: "https://www.theodinproject.com", badge: "🆓", status: "✅", why: "Free full-stack path; portfolio can become freelance proof." },
			{ name: "FullStackOpen", url: "https://fullstackopen.com", badge: "🆓", status: "✅", why: "Free React/Node course from the University of Helsinki." },
			{ name: "JavaScript.info", url: "https://javascript.info", badge: "🆓", status: "✅", why: "Best free JS tutorial, chapter by chapter." },
			{ name: "MDN", url: "https://developer.mozilla.org", badge: "🆓", status: "✅", why: "The web docs; bookmark for life." },
			{ name: "MS AI-For-Beginners", url: "https://github.com/microsoft/AI-For-Beginners", badge: "🆓", status: "✅", why: "Free AI curriculum with labs." },
			{ name: "MS ML-For-Beginners", url: "https://github.com/microsoft/ML-For-Beginners", badge: "🆓", status: "✅", why: "Gentler ML on-ramp." },
			{ name: "LLM Course", url: "https://github.com/mlabonne/llm-course", badge: "🆓", status: "✅", why: "Free roadmap into LLM engineering." },
			{ name: "Anki", url: "https://apps.ankiweb.net", badge: "🆓", status: "✅", why: "Spaced-repetition flashcards for +2, medical, and engineering exams." },
			{ name: "AnkiDroid", url: "https://github.com/ankidroid/Anki-Android", badge: "🆓", status: "✅", why: "Free Anki on Android. Note that the iOS app is paid." },
			{ name: "Wolfram Alpha", url: "https://www.wolframalpha.com", badge: "🔶", status: "✅", why: "Computational answers for math and physics." },
			{ name: "Project Gutenberg", url: "https://www.gutenberg.org", badge: "🆓", status: "✅", why: "70k+ free legal ebooks." },
			{ name: "Open Library", url: "https://openlibrary.org", badge: "🆓", status: "🌐", why: "Borrow scanned books free; confirm in browser before publishing claims." },
			{ name: "Standard Ebooks", url: "https://standardebooks.org", badge: "🆓", status: "✅", why: "Beautifully formatted public-domain ebooks." },
			{ name: "OpenStax", url: "https://openstax.org", badge: "🆓", status: "✅", why: "Free peer-reviewed college textbooks." },
			{ name: "Open Textbook Library", url: "https://open.umn.edu/opentextbooks", badge: "🆓", status: "✅", why: "More free textbooks by subject." },
			{ name: "Free Programming Books", url: "https://ebookfoundation.github.io/free-programming-books-search", badge: "🆓", status: "✅", why: "Search every free coding book." },
			{ name: "IndiaBIX", url: "https://www.indiabix.com", badge: "🆓", status: "✅", why: "Aptitude tests for job exams and interviews." },
			{ name: "EFSET", url: "https://www.efset.org", badge: "🆓", status: "✅", why: "Free English certificate for CVs and Upwork." },
			{ name: "YouGlish", url: "https://youglish.com", badge: "🆓", status: "✅", why: "Hear any English word pronounced in real videos." },
			{ name: "OneLook", url: "https://onelook.com", badge: "🆓", status: "✅", why: "Multi-dictionary search in one box." },
		],
	},
];

export const monthlyPicks = [
	{ name: "DeepSeek", categoryId: "ai-tools", badge: "🆓", what: "A strong free AI tutor for code and math.", why: "Great for CS students on a zero-NPR budget." },
	{ name: "Harper", categoryId: "ai-tools", badge: "🆓", what: "Private grammar checking for proposals and CVs.", why: "Polishes client English without adding another paid subscription." },
	{ name: "Photopea", categoryId: "business", badge: "🆓", what: "Photoshop-style editing in your browser.", why: "Make menus, price lists, and social posts from a shop laptop." },
	{ name: "Hostinger", categoryId: "hosting", badge: "💳 Affiliate", what: "Beginner-friendly paid hosting.", why: "Useful when Nepali bloggers outgrow free static hosting." },
	{ name: "Payoneer guide", categoryId: "payments", badge: "🔶", what: "USD receiving workflow for freelancers.", why: "Needs frequent fee checks, but it is a key Nepal earning pipeline." },
	{ name: "Anki", categoryId: "students", badge: "🆓", what: "Spaced repetition for exams.", why: "Works offline and helps +2, medical, and engineering students retain more." },
];

export function getCategory(id) {
	return resourceCategories.find((category) => category.id === id);
}

export function resourceHref(resource) {
	if (resource.env && typeof process !== "undefined") {
		return process.env[resource.env] || null;
	}
	return resource.url || null;
}
